apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: jx-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    url: https://github.com/jstrachan/environment-jstrachan-kp20-production.git
  teamSettings: {}
status: {}
