apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: staging
spec:
  kind: Permanent
  label: Staging
  namespace: jx-staging
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    url: https://github.com/jstrachan/environment-jstrachan-kp20-staging.git
  teamSettings: {}
status: {}
